from portfolio_tabs.holdings_tab import holdings_tab as render_holdings_tab
from portfolio_tabs.performance_tab import performance_tab as render_performance_tab
from portfolio_tabs.allocation_tab import allocation_tab as render_allocation_tab
from portfolio_tabs.dividends_tab import dividends_tab as render_dividends_tab
from portfolio_tabs.add_transaction_tab import add_transaction_tab as render_add_transaction_tab
