[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1llgRNZbHiPdtDZFNGV5oxX13adXo1ufIVMiGBDbB8Rg/edit?usp=sharing"
worksheet=0

[[expense_tracker.owners]]
name = "Owner 1"
color = "#da70d6" 

[[expense_trackers.owners]] 
name = "Owner 2" 
color = "#00bfff"

[expense_tracker.transaction_tab.defaults] 
shared = true

[[expense_tracker.transaction_tab.presets]]
memo = "Income" 
category = "Income" 
owner = "Owner 1" 
price = 1500
payment_method = "Check" 
shared = false

[[expense_tracker.transaction_tab.presets]] 
memo = "Internet Subscription"
category = "Internet" 
owner = "Owner 2" 
price = 50 
payment_method = "Credit" 
shared = true 
