[connections.gsheets]
spreadsheet = ""
worksheet = 0 

[[expense_tracker.owners]]
name = "Owner A"
color = "#da70d6" 

[[expense_trackers.owners]] 
name = "Owner 2" 
color = "#00bfff"

[expense_tracker.transaction_tab.defaults] 
shared = true
