[connections.gsheets]
spreadsheet = ""
worksheet = 0 

[[expense_tracker.owners]]
name = "Owner A"
color = "#da70d6" 

[[expense_trackers.owners]] 
name = "Owner B" 
color = "#00bfff"

[expense_tracker.transaction_tab.defaults] 
shared = true

[[expense_tracker.transaction_tab.presets]]
memo = "Income" 
category = "Income" 
owner = "Owner A" 
price = 1500
payment_method = "Check" 
shared = false

[[expense_tracker.transaction_tab.presets]] 
memo = "Internet Subscription"
category = "Internet" 
owner = "Owner B" 
price = 50 
payment_method = "Credit" 
shared = true 
